### ISSUE TITLE
Continually prompted for captcha

### ISSUE THREAD

**Issue by walthowd** [Apollon77/alexa-cookie#1]
Continuing conversation from https://github.com/thorsten-gehrig/alexa-remote-control/issues/10#issuecomment-403954210

I'm using your provided example code:

```
let Alexa = require('alexa-remote');
let alexa = new Alexa();

/***************************************************************/
// see: https://www.gehrig.info/alexa/Alexa.html
// cookie starts with x-amzn-dat and ends with =" csrf=12345780
let cookie = 'x-amzn-dat.../ /...=" csrf=12345780';

alexa.init({
        cookie: cookie,  // cookie if already known, else can be generated using email/password
        email: 'myemail@gmail.com', // optional, amazon email for login to get new cookie
        password: 'XXXX', // optional, amazon password for login to get new cookie
        bluetooth: true,
        logger: console.log, // optional
        baseUrl: 'pitangui.amazon.com' // optional, e.g. "pitangui.amazon.com" for amazon.com, default is "layla.amazon.de"
    },
    function (err) {
        if (err) {
            console.log(err);
            return;
        }
        for (let device of this.devices) {
            console.log (device._name);
        }
    }
);
```

But I continually receive this output:

```
Error: Captcha needed
    at request (/Users/whowd/Dropbox/Desktop/alexa-remote/node_modules/alexa-cookie/alexa-cookie.js:187:31)
    at IncomingMessage.<anonymous> (/Users/whowd/Dropbox/Desktop/alexa-remote/node_modules/alexa-cookie/alexa-cookie.js:69:33)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I have tried an incognito Chrome browser with JS disabled and logging into Alexa.Amazon.com. After getting prompted for the captcha, I logon and receive a white screen and then try running the example code again, but still receive the captcha prompt. 

I can post the full output of the example script, but wasn't sure if I needed to sanitize any of the encoded or hashed text. Thanks.

**Comment by Apollon77** [comment]
Please update your repo. I fixed today the error that cases the crash, but still the errr stays the same.

As in thorsten-gehrig/alexa-remote-control I have no solution for you when amazon still requests the captcha. This lib is doing exactly the same as the shell script.

So how can I help here?

**Comment by walthowd** [comment]
I pulled the latest from the last push.

Not sure if there is any help, just providing some feedback on the status for US users. It seems the only work around would be to implement a javascript compatible web logon method as the captcha seems to occur when using a non JS capable logon method/browser.

**Comment by Apollon77** [comment]
Puhhhh ... for now: I‘m happy to take PRs ;-))

Any idea how to accomplish that?

**Comment by Apollon77** [comment]
I got a report that changing User agent to 

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

Worked for some users on Linux systems that needed to provide captcha before. 
Maybe try it?!

**Comment by Apollon77** [comment]
And btw did you also tried changing accept-language used in Alexa-cookie class? 
I should also allow overwriting it from Alexa-remote ...

**Comment by Apollon77** [comment]
also see updated docs and version on github

**Comment by walthowd** [comment]
Thank you for the ideas and suggestions. I pulled the latest and tested, with the same results. I had always been changing the accept-langauge to en-US. I then tried the different User Agent and again had the same results. 

I also tried on a separate system on a completely different network with the same results. 

On my home system, I can use the original shell script without any issue (using the cookie) but if I try  to use alexa-remote I always receive the captcha prompt:

```
[HowdiMac:~/alexa-remote] hass$ node example2.js
....
Alexa-Cookie: Response (200)
Error: Captcha needed
    at request (/Users/hass/alexa-remote/node_modules/alexa-cookie/alexa-cookie.js:191:31)
    at IncomingMessage.<anonymous> (/Users/hass/alexa-remote/node_modules/alexa-cookie/alexa-cookie.js:69:33)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)

[HowdiMac:~/alexa-remote] hass$ ~/.homeassistant/alexa_remote_control.sh -a
the following devices exist in your account:
Dawn's Alexa Apps
Kitchen Dot
Walt's Reverb.ai
Walt's echosim_BETA
Family room Dot
Everywhere
Master bedroom Dot
Colin's room
This Device
Walt's Alexa Apps
```

**Comment by walthowd** [comment]
Looking through the code here for OpenHAB trying to see if they are doing anything differently, as most of the OpenHAB users don't report getting prompted for captchas on logon:

https://github.com/openhab/openhab2-addons/blob/f54c9b85016758ff6d271b62d255bbe41a027928/addons/binding/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/Connection.java#L442

**Comment by Apollon77** [comment]
Interesting, but in fact they have the same handling. They only detect the error message better :-)

... wait there is one thing: They add one header for the login POST request: https://github.com/openhab/openhab2-addons/blob/f54c9b85016758ff6d271b62d255bbe41a027928/addons/binding/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/Connection.java#L345

Please try one thing:Add in alexa-cookie.js after https://github.com/Apollon77/alexa-cookie/blob/master/alexa-cookie.js#L177 an

if (options.method === 'POST') options.headers.Expect = '100-continue';

and try again. you can also try their user-agent.

**Comment by Apollon77** [comment]
BTW: The only thing they do different is that they really provide a proxy server to login and maybe solve the captcha, with this they provide a real login flow with e.g. the user-agent they use and so have a better chance. to build this is a bigger effort ... need to see when I would find time for something like this

**Comment by walthowd** [comment]
Thanks, tried those options as well, still no luck:

```
Alexa-Cookie: Step 3: login with filled form, referer contains session id
Alexa-Cookie: Sending Request with {"host":"www.amazon.com","path":"/ap/signin","method":"POST","headers":{"DNT":"1","Upgrade-Insecure-Requests":"1","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0","Accept-Language":"en-US","Connection":"keep-alive","Content-Type":"application/x-www-form-urlencoded","Referer":"https://www.amazon.com/ap/signin/137-5904191-7239725","Cookie":"session-id=137-5904191-7239725; session-id-time=2162147247l; ubid-main=131-4321214-5047759","Accept":"*/*","Expect":"100-continue"},"gzip":true,"body":"appActionToken=ctRI7UIUj2FVc1uK5j2FtjejqG7t9Uwj3D&appAction=SIGNIN&showRmrMe=ape%3AMQ%3D%3D&openid.return_to=ape%3AaHR0cHM6Ly9hbGV4YS5hbWF6b24uY29tLw%3D%3D&prevRID=ape%3ASjMzWDREUktSTTE5MTVZTVZUVzA%3D&openid.identity=ape%3AaHR0cDovL3NwZWNzLm9wZW5pZC5uZXQvYXV0aC8yLjAvaWRlbnRpZmllcl9zZWxlY3Q%3D&openid.assoc_handle=ape%3AYW16bl9kcF9wcm9qZWN0X2RlZQ%3D%3D&openid.mode=ape%3AY2hlY2tpZF9zZXR1cA%3D%3D&failedSignInCount=ape%3AMA%3D%3D&openid.claimed_id=ape%3AaHR0cDovL3NwZWNzLm9wZW5pZC5uZXQvYXV0aC8yLjAvaWRlbnRpZmllcl9zZWxlY3Q%3D&pageId=ape%3AYW16bl9kcF9wcm9qZWN0X2RlZQ%3D%3D&openid.ns=ape%3AaHR0cDovL3NwZWNzLm9wZW5pZC5uZXQvYXV0aC8yLjA%3D&showPasswordChecked=false&email=myemail%40gmail.com&password=XXXX"}
Alexa-Cookie: Response (200)
Error: Captcha needed
    at request (/Users/whowd/Dropbox/Desktop/alexa-remote/node_modules/alexa-cookie/alexa-cookie.js:192:31)
    at IncomingMessage.<anonymous> (/Users/whowd/Dropbox/Desktop/alexa-remote/node_modules/alexa-cookie/alexa-cookie.js:69:33)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by Apollon77** [comment]
:-(

**Comment by walthowd** [comment]
Yup, probably no good resolution to this issue for the time being. Thanks for helping me look into it.

**Comment by Apollon77** [comment]
Let's leave it open ... maybe I find time soon

**Comment by Apollon77** [comment]
Stay tuned. I think I managed the proxy thing ;-)))
I now "only" need to integrate that into the cookie ... lib ... so maybe 1-2days more with testing and such

**Comment by walthowd** [comment]
oooooh

**Comment by Apollon77** [comment]
Ok, here you go ... alexa-remote and alexa-cookie are as 0.2.0 on Github.
So please update. see the new parameter for "proxy*" from alexa-cookie readme and add them to you options in alexa-remote.

Then log to console as in example and I'm happy to get a debug log ... if you do not want to post here send me as email to ingo@fischer-ka.de

**Comment by walthowd** [comment]
Wow, this looks great. Thanks for the hard work of putting this together.  I e-mailed you the full debug logs. On first run, the example code below errors out as result.cookie is not defined. 

```
alexaCookie.generateAlexaCookie('amazon-email', 'password', options, function (err, result) {
    // IMPORTANT: can be called multiple times!! As soon as na new cookie is fetched or an error happened. Consider that!
    console.log('cookie: ' + result.cookie);
    console.log('csrf: '   + result.csrf);
    if (result.csrf) {
        alexaCookie.stopProxyServer();
    }
});
```

I commented out everything referencing **result** and I believe I got through and generated a cookie using the browser, though the browser did redirect to http://true/spa/index.html after submitting the form.

**Comment by Apollon77** [comment]
change the one line to 

    if (result && result.csrf) {

then the error is gone :-) I fix the example.

Can you please add one flaog to the options and resend log (will be much more detailed but I would like to compare the flow tih german Amazon so make sure everything is correct):

proxyLogLevel: 'debug'

Thank you!

**Comment by Apollon77** [comment]
BTW: don't need log ... enough to see :-)

Geat then I close here? :-)

**Comment by walthowd** [comment]
Actually, looks like it's not fully dumping out the cookie. The function never quits and result.cookie is never populated. I will email you full debug logs. 

```
const alexaCookie = require('alexa-cookie');

const options = { // options is optional at all
    logger: console.log,       // optional: Logger instance to get (debug) logs
    amazonPage: 'amazon.com',  // optional: possible to use with different countries, default is 'amazon.de'
    acceptLanguage: 'en-US',   // optional: webpage language, should match to amazon-Page, default is 'de-DE'
    setupProxy: true,          // optional: should the library setup a proxy to get cookie when automatic way did not worked? Default false!
    proxyOwnIp: '150.243.163.55',         // required if proxy enabled: provide own IP or hostname to later access the proxy. needed to setup all rewriting and proxy stuff internally
    proxyPort: 3456,           // optional: use this port for the proxy, default is 0 means random port is selected
    proxyListenBind: '0.0.0.0',// optional: set this to bind the proxy to a special IP, default is '0.0.0.0'
    proxyLogLevel: 'debug'      // optional: Loglevel of Proxy, default 'warn'
}

alexaCookie.generateAlexaCookie('myemail@gmail.com', 'XXXX', options, function (err, result) {
    // IMPORTANT: can be called multiple times!! As soon as na new cookie is fetched or an error happened. Consider that!
    if (result) {
        console.log('your cookie: ' + result.cookie);
    	console.log('your csrf: '   + result.csrf);
    	if (result.csrf) {
        	alexaCookie.stopProxyServer();
    	}
    } else {
	   console.log('no result yet');
    }
});
```

**Comment by Apollon77** [comment]
Can it be that for last call the hard coded „layla“ server is wrong ? Was that not pitangu for us?!

Can you try change that manually please and try?

**Comment by walthowd** [comment]
Emailed you full debug log after changing line 141 of alexa-cookie.js to:

`         'host': 'pitangui.' + _options.amazonPage,`

**Comment by walthowd** [comment]
I emailed you what I see in the browser. It looks like everything works but the final redirect is blank page with the URI http://true/spa/index.html

**Comment by Apollon77** [comment]
Will check later when kids are in bed

**Comment by Apollon77** [comment]
there still was a place where i forgot to replace the ".de" :-) and it was exactly the comparism if done :-)

I still do not understand the http://true/... path but ok :-)

Please update from github and retry.

please also see new config option called 

alexaServiceHost

where you can set the "pitangui.amazon.com" as value to be used

**Comment by walthowd** [comment]
It works perfectly! Do you want/need any debug logs?

**Comment by walthowd** [comment]
I e-mailed you the full debug log of a successful proxy cookie retrieval.  

Thanks again for all of your hard work -- I'm planning on trying to create some Node-RED module/packages that incorporate your libraries.  This will allow Node-RED and Home Automation (Home Assistant, openHAB, etc) to tie into Alexa.

https://nodered.org/docs/creating-nodes/packaging

**Comment by Apollon77** [comment]
cool. openHab already have their own integration , but HASS may be interested .

I will publish the library soon to npm a "alexa-cookie2" and "alexa-remote2" ... because thenames without "2" are used by the other developer that disappeared :-(

**Comment by Apollon77** [comment]
Log is great. thank you!

**Comment by Apollon77** [comment]
This is a library, meaned to be integrated in your own Javascript stuff. With the exmaple script you can also use it once and then do with the cookie what you want, but this is just a side effect :-)
ALso alexa-remote is only library and it seems that the info there (x-amzn-dat...) is outdated because you are right in the current cookies this is no longer included.

**Comment by jonferreira** [comment]
Yes I understand that, thanks

I'm using alexa-cookie2 to - hopefully - generate the cookie to use with alexa-remote2. The cookie generated by alexa-cookie2 starts with "session-id=" and ends with "csrf=-688817323" but when I use that with alexa-remote2 it fails with:

> Alexa-Remote WS-MQTT: Cookie incomplete : null
> /home/pi/alexa_remote.js:25
>         for (let device of this.devices) {
>                              ^
> 
> TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
>     at AlexaRemote.<anonymous> (/home/pi/alexa_remote.js:25:30)
>     at prepare (/home/pi/node_modules/alexa-remote2/alexa-remote.js:120:33)
>     at AlexaRemote.initNotifications (/home/pi/node_modules/alexa-remote2/alexa-remote.js:147:62)
>     at initBluetoothState (/home/pi/node_modules/alexa-remote2/alexa-remote.js:138:30)
>     at getBluetooth (/home/pi/node_modules/alexa-remote2/alexa-remote.js:262:29)
>     at IncomingMessage.res.on.e (/home/pi/node_modules/alexa-remote2/alexa-remote.js:653:58)
>     at emitNone (events.js:91:20)
>     at IncomingMessage.emit (events.js:185:7)
>     at endReadableNT (_stream_readable.js:975:12)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)

I have the feeling I'm missing something obvious

**Comment by Apollon77** [comment]
initialize alexa-remote with a logger-key in options and post full log please

**Comment by jonferreira** [comment]
I have logger set to console.log which outputs the result on the screen. also added a console.log(this) right before the error which seems to output a response but without a this.devices.

Should I copy paste this and send it to you? direct message possible?

**Comment by Apollon77** [comment]
send to github@fischer-ka.de

**Comment by Apollon77** [comment]
Ok, the code is wrong in this case ... makes no sense (and yes so the example is wrong)

better use: 

Object.keys(alexa.serialNumbers)

to iterate over them. And with "alexa.find(oneservialnumber)" you can also get the object will everything.

Please try and post the working code for this part then I will update it in example :))

**Comment by jonferreira** [comment]
Yes I seem to have a different response than what was expected which doesn't make sense! If I go to https://alexa.amazon.com/api/devices-v2/device?cached=false I do have the response formatted with a devices array as expeted

**Comment by jonferreira** [comment]
Regarding your reply, I can of course change the "default" code on the alexa.init() callback but I'm more interested in knowing why the response I get is different and what problems I can find down the road?

For example my main goal is to send TTS and hopefully tell Alexa to "play XXX on spotify". By reading your code I think this would be done with this.sendSequenceCommand("name", "speak", "test"); but presumably it would fail because it can't find device "name"?

**Comment by Apollon77** [comment]
Ok, if you want to have that one device array then simply use "alexa.getDevices()" method and you get exactly that.
The library internally prepares some data and strujtures and device objects too (that also come out of this) so you can choose what to use.

device name is simply the serialnumber of the device.

and "speak" is NOT to tell Alexa what to do, but to have Alexa speak out the text you gave there!

playing tuneine os more complex

In fact the documentation of the lib is a big todo on my side and I need to find time for it

**Comment by jonferreira** [comment]
Yes detailed documentation would be welcome!

>and "speak" is NOT to tell Alexa what to do, but to have Alexa speak out the text you gave there!
Yes, that's what I meant, i.e. to send TTS notifications. I also want - if possible - to "tell her" to "play xxx on spotify" - will have to dig through your code to see if / how that's possible!

>Ok, if you want to have that one device array then simply use "alexa.getDevices()" method and you get exactly that.
OK then so if I got this right it means the example is incomplete then? this .devices() won't exist unless we run this.getDevices()?

Would it be too much of an hassle if you could share a working example of:
a) listing all devices 
b) make alexa "play xxx on spotify"

**Comment by jonferreira** [comment]
for what is worth the following seems to work to send TTS 

```
alexa.init({
...
function (err) {
        if (err) {
            console.log (err);
            return;
        }
	//this.getDevices();
this.sendSequenceCommand("G090QU0674250K5P", "speak", "It worked, it finally worked!", function(result){
	console.log(result);
});
    }
);
```

even though I get an error

```
Alexa-Remote: Response: No body
Error: no body
    at IncomingMessage.res.on.e (/home/pi/node_modules/alexa-remote2/alexa-remote.js:644:69)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by Apollon77** [comment]
a.) iterate over alexa.serialNumbers object. key is serialnumber, value is a device object which is an "enhanced" version of the json
b) use alexa.getDevices((err, result) => {...}) to get the plain devices object from Amazon without any enhancements.

c.) the callback from nearly all commands are error-first, so:

this.sendSequenceCommand("G090QU0674250K5P", "speak", "It worked, it finally worked!", function(error, result){
	console.log(result);
});

is the correct way and yes some calls are simply not answered by amazon and so an error like "no body" can be a valid result... one example is that sendSequenceCommand method ... maybe I could find all methods out that are that way and "transform" the error ... could be convenient

**Comment by jonferreira** [comment]
OK thanks, sounds like it would be pretty complex - if even possible - just to get something like "play ACDC in spotify"  to work :(

**Comment by Apollon77** [comment]
You can also hardcode it ;-)

Check the name of the music provider you want  and then you can call the method.

**Comment by jonferreira** [comment]
Yeah I figured that would be possible but to be honest, I'm completely lost without any documentation :(

If you happen to have an example start to finish on how to do it, i.e. make alexa play XXX on spotify, I'd be grateful!

**Comment by Apollon77** [comment]
will try to find some time for a complete example/docs, but as short help:

call 

```
alexa.getMusicProviders((err, providers) => { }...);
```

The response data in providers from getting all music providers for my accounts returns:

```
[{"displayName":"My Library","supportedTriggers":[],"icon":null,"supportedProperties":["Alexa.Music.PlaySearchPhrase"],"id":"CLOUDPLAYER","supportedOperations":["Alexa.Music.PlaySearchPhrase"],"availability":"AVAILABLE","description":"Music provider"},{"displayName":"Amazon Music","supportedTriggers":[],"icon":null,"supportedProperties":["Alexa.Music.PlaySearchPhrase"],"id":"AMAZON_MUSIC","supportedOperations":["Alexa.Music.PlaySearchPhrase"],"availability":"AVAILABLE","description":"Music provider"},{"displayName":"TuneIn","supportedTriggers":[],"icon":null,"supportedProperties":["Alexa.Music.PlaySearchPhrase"],"id":"TUNEIN","supportedOperations":["Alexa.Music.PlaySearchPhrase"],"availability":"AVAILABLE","description":"Music provider"}]
```

(I have no Spotify sorry) so in fact the call it for your account. You need the "id" from spotify one ... I expect it to be "SPOTIFY" but do not 100% know :-)

After this

```
alexa.playMusicProvider(deviceSerial, 'SPOTIFY' /*or whatever the id is*/, 'XXX', (err, res) => {});
```

should be equivalent for "play XXX on spoitfy"

**Comment by jonferreira** [comment]
you sir are a legend!

```
alexa.sendMessage("Echo", 'volume', '30', (err, res) => {
console.log(err);
console.log(res);
});

alexa.playMusicProvider("Echo", 'SPOTIFY', 'ACDC', (err, res) => {
console.log(err);
console.log(res);
});
```

I still have that "no body" error output but works wonders! 

I've completely hijacked this issue now so will probably open a few other "issues" with more questions, such as how to use MQTT etc

@walthowd have you started working on the node-red node?

**Comment by jonferreira** [comment]
In case there's anyone interested, https://www.npmjs.com/package/red-contrib-alexa-remote

**Comment by walthowd** [comment]
@jonferreira I've got the bare shell of a wrapping it into Node-RED started but haven't had much time to pursue it lately....

**Comment by Apollon77** [comment]
Good to know. Now I should not break things that often ;-)
Will try to find time for docs ... I‘m also happy about PRs ;-))) (ok it was a try ...)

**Comment by jonferreira** [comment]
@walthowd I have a basic yet fully functioning node-red "wrapper" for alexa-remote2 sendMessage, playMusicProvider and speak commands here https://www.npmjs.com/package/node-red-contrib-alexa-remote

There's LOTS that can be improved but for now does everything I need. Would be great to get alexa-cookie on node-red as well :)
