### ISSUE TITLE
Can this be modified to get the cookie from eltern.amazon.de?

### ISSUE THREAD

**Issue by Xento** [Apollon77/alexa-cookie#128]
I'm thinking of writing a nodejs lib which can login to eltern.amazon.de and set the settings for the tablets.
Maybe you could help me with modifying this lib for the other domain.

**Comment by Apollon77** [comment]
Honestly, I have no idea and thids would be needed to be checked.

**Comment by Xento** [comment]
I think I will try https://github.com/alandtse/auth_capture_proxy
There you only need to change the url and than the proxy just works.
