### ISSUE TITLE
How is this used?

### ISSUE THREAD

**Issue by dustball** [Apollon77/alexa-cookie#16]
Looks like great code, and I'm experience JS developer but only client side and don't know node/npm.

What commands does one run to use this?  My end goal is to control alexa via mac command line. I have node/npm installed via brew.  Thanks!

**Comment by Apollon77** [comment]
In fact, see example :-)

This lib only takes care of the cookie stuff, so the basics for controlling. Maybe check Alexa-Remote Library also from me. There all functions for controlling exist. Also an example is there, but Beside a ver Basic example I did not had time for documentation - means check the code tinder the available functions. Sorry.
