### ISSUE TITLE
Amazon Auth Flow Change

### ISSUE THREAD

**Issue by tonesto7** [Apollon77/alexa-cookie#3]
I've been using a modified version of this proxy and today noticed that no long works.  It just redirects back the primary alexa.amazon.com web page.

**Comment by Apollon77** [comment]
Did you tried very current version on npm. I updated some days ago ... do this version work for you?

**Comment by Apollon77** [comment]
To be exact: is 1.0.1 working for you?

**Comment by tonesto7** [comment]
Yes I merged in the latest changes.  Really the only change i made was to pass the express instance from outside the proxy to be used inside so I can run it on Heroku

**Comment by tonesto7** [comment]
I confirmed with a fresh clone of your repo and ran the example.  Yours redirects back to the https:/spa/index.html

**Comment by tonesto7** [comment]
I knew I should have kept some of the old session requests.  They would be helpful in comparing to the ones

**Comment by Apollon77** [comment]
Ok this Matches to some other reports :-( is tart hating amazon (or the idea for this lib). I will check. 

Additionally I work on „the solution“ ;-) then you only need to use proxy once and then can refresh the cookies via an other way. Expect a big update of the lib soon too.

**Comment by tonesto7** [comment]
Thanks for this amazing library... I appreciate the work

**Comment by tonesto7** [comment]
This is horrible timing on Amazon part because I used the library to get the auth cookie for the SmartThings Integration I put together.  (I just released it 3 days ago)

**Comment by tonesto7** [comment]
@apollon77
I just tried using your example and it worked.

No only difference between mine and yours now is that mine listens on the /proxy path  

I’m a pretty good developer but I really struggle with this proxy crap especially when it comes to doing re-write.  Would you mind looking at my file and tell me what you think

https://github.com/tonesto7/echo-speaks-server/blob/master/alexa-cookie/alexa-cookie.js

**Comment by Apollon77** [comment]
it's Amazon fail ... (or their way to handle our hacks). They really return a redirect to the listed url:

```
"headers": {
          "server": "Server",
          "date": "Fri, 16 Nov 2018 22:45:16 GMT",
          "content-length": "20",
          "connection": "close",
          "x-amzn-requestid": "4949499b-e9f1-11e8-9018-03f4637dda9f",
          "content-encoding": "gzip",
          "location": "https:/spa/index.html",
          "x-amz-rid": "PMZBD3JDMTC8J2S96ZXH",
          "vary": "Accept-Encoding,X-Amzn-CDN-Cache,User-Agent"
        },

```

**Comment by Apollon77** [comment]
Or they "use" how browser work ... I try something ...

**Comment by Apollon77** [comment]
So, try it ... small changes but seems to help

**Comment by Apollon77** [comment]
please report back ... i would wait before releasing to npm

**Comment by Apollon77** [comment]
ok, needed to release it :-) no problem ... can only be better ...

**Comment by tonesto7** [comment]
@Apollon77 
Can you tell me why it's not working anymore when I use the path /proxy instead of /
After the login page, it redirects back to amazon.com/ap/signin

https://gist.github.com/tonesto7/a38e99734c7e4baab316ff02b3bccfc7

Also do you have a donation link?  I would love to donate for your efforts :)

**Comment by Apollon77** [comment]
Hm ... can you provide logs from proxyLog set to "info" from such a try (or better full debug would also be ok) :-) if you like more privacy send to iobroker@fischer-ka.de .

Donation  ... wow ... like this idea :-) also send me email and I tell you my paypal :-)

**Comment by tonesto7** [comment]
@Apollon77  I've sent you an email...

**Comment by Apollon77** [comment]
1.0.3 with further small optimizations released
