### ISSUE TITLE
Error "Alexa-Cookie: Response (401)"

### ISSUE THREAD

**Issue by naka-kazz** [Apollon77/alexa-cookie#42]
I want to get alexa cookie from alexa.amazon.co.jp. So, I modified "amazon.com" to "amazon.co.jp" in alexa-cookie.js. But, I could not get cookie with following message.
Now, I don't have any idea to solve this error. Thank you for your advice.

My enviroment:
-node: v10.16.0
-npm: 6.12.0
-Alexa-cookie:3.0.3

Alexa-Cookie: Get User data
{"host":"alexa.amazon.co.jp","path":"/api/users/me?platform=ios&version=2.2.223830.0","method":"GET","headers":{"User-Agent":"AmazonWebView/Amazon Alexa/2.2.223830.0/iOS/11.4.1/iPhone","Accept-Language":"ja-JP","Accept-Charset":"utf-8","Connection":"keep-alive","Accept":"application/json","Cookie":"session-id=131-2011528-2571913; session-id-time=2219020446l; session-token=MFNM0t6MKnaQbqfbG2qef3ipXQ1ADGtdOug/sY5n1ZFRkPcaJWySPa4F0jgwIeibKVM6JnvJx4oKDZw+k+HS5pXSdxrwo4kKRALzXp/57IPyhzOQQF7pzLIt+mjU7uSTiCR9MvxoOYyPAibdkocGeGlu6iLdPf2njXqLXSYRbh5QQxW0x9PhWIiu3/R2r/MDjyYJBZtTRLbxjzWuRKHr82iXuBrGmz4g; ubid-main=135-4077134-3964217; csm-hit=tb:AJGBWYMWKQ7V159ZK2PQ+s-4VXT930QF477M6CRC2NH|1588300011515&t:1588300011515&adb:adblk_no; sid=koSjY7PGWBgGZrq2pt+0Tw==|P7QToSV7Oo4Q+lAIUFe2J4lDoWCCZPcmeq+BNs6Keuk=; frc=miKb5GjxemgtqPxrhDmwHDUD7LawQKDuv3/gv5zmRg0t36QUhO6QW+bdvrrwUH6JsFfJ1hopvMmqxhCBI7rrIqAIOiy0ZU3C7deFsztXVmn4vVWTRyZI7AAda4tiVJNRkAxR4mIjPCJjChvJGWccJwJOS8sejG1dcgodOUf4BuU8vbEKrlQlPLwkc8GtGnn3xe9UtgsIyyDc10m2h0mVh7pfRK7vkppcRuOOYpY8yi9opptlCz+z04hexu4uJ3kGCcNRtDOVRc7BgGV7bT+Jllbb6iq6y7iT9TWnuzTnGL0HcKvGVp7Td0i3rAmMknCfZuEgr/FKvKcTjYQvLl6EUoIfP5slwoHO+iFYeRC2KKHh2xtcmobr7FZUo53BUFNPPR912IurX8ntzaxqHXykHnA9E+F57rkf8g==; map-md=eyJkZXZpY2VfdXNlcl9kaWN0aW9uYXJ5IjpbXSwiZGV2aWNlX3JlZ2lzdHJhdGlvbl9kYXRhIjp7InNvZnR3YXJlX3ZlcnNpb24iOiIxIn0sImFwcF9pZGVudGlmaWVyIjp7ImFwcF92ZXJzaW9uIjoiMi4yLjIyMzgzMCIsImJ1bmRsZV9pZCI6ImNvbS5hbWF6b24uZWNobyJ9fQ=="}}
Alexa-Cookie: Sending Request with {"host":"alexa.amazon.co.jp","path":"/api/users/me?platform=ios&version=2.2.223830.0","method":"GET","headers":{"User-Agent":"AmazonWebView/Amazon Alexa/2.2.223830.0/iOS/11.4.1/iPhone","Accept-Language":"ja-JP","Accept-Charset":"utf-8","Connection":"keep-alive","Accept":"application/json","Cookie":"session-id=131-2011528-2571913; session-id-time=2219020446l; session-token=MFNM0t6MKnaQbqfbG2qef3ipXQ1ADGtdOug/sY5n1ZFRkPcaJWySPa4F0jgwIeibKVM6JnvJx4oKDZw+k+HS5pXSdxrwo4kKRALzXp/57IPyhzOQQF7pzLIt+mjU7uSTiCR9MvxoOYyPAibdkocGeGlu6iLdPf2njXqLXSYRbh5QQxW0x9PhWIiu3/R2r/MDjyYJBZtTRLbxjzWuRKHr82iXuBrGmz4g; ubid-main=135-4077134-3964217; csm-hit=tb:AJGBWYMWKQ7V159ZK2PQ+s-4VXT930QF477M6CRC2NH|1588300011515&t:1588300011515&adb:adblk_no; sid=koSjY7PGWBgGZrq2pt+0Tw==|P7QToSV7Oo4Q+lAIUFe2J4lDoWCCZPcmeq+BNs6Keuk=; frc=miKb5GjxemgtqPxrhDmwHDUD7LawQKDuv3/gv5zmRg0t36QUhO6QW+bdvrrwUH6JsFfJ1hopvMmqxhCBI7rrIqAIOiy0ZU3C7deFsztXVmn4vVWTRyZI7AAda4tiVJNRkAxR4mIjPCJjChvJGWccJwJOS8sejG1dcgodOUf4BuU8vbEKrlQlPLwkc8GtGnn3xe9UtgsIyyDc10m2h0mVh7pfRK7vkppcRuOOYpY8yi9opptlCz+z04hexu4uJ3kGCcNRtDOVRc7BgGV7bT+Jllbb6iq6y7iT9TWnuzTnGL0HcKvGVp7Td0i3rAmMknCfZuEgr/FKvKcTjYQvLl6EUoIfP5slwoHO+iFYeRC2KKHh2xtcmobr7FZUo53BUFNPPR912IurX8ntzaxqHXykHnA9E+F57rkf8g==; map-md=eyJkZXZpY2VfdXNlcl9kaWN0aW9uYXJ5IjpbXSwiZGV2aWNlX3JlZ2lzdHJhdGlvbl9kYXRhIjp7InNvZnR3YXJlX3ZlcnNpb24iOiIxIn0sImFwcF9pZGVudGlmaWVyIjp7ImFwcF92ZXJzaW9uIjoiMi4yLjIyMzgzMCIsImJ1bmRsZV9pZCI6ImNvbS5hbWF6b24uZWNobyJ9fQ=="}}
Alexa-Cookie: Response (401)
Get User data Response: ""
RESULT: SyntaxError: Unexpected end of JSON input / null

**Comment by Apollon77** [comment]
First of all why you do not use the provided api and parameters in the object when using it instead of changing files?

In generell i think it is not that easy. I can try to google a bit for correct domain names and such. Also locale needs to be correct

**Comment by naka-kazz** [comment]
Thank you for response. The alexa account is different between alexa.amazon.com and alexa.amazon.co.jp. So, Japanese users have to login alexa.amazon.co.jp. But, I think, alexa host(alexa.amazon.co.jp) are not be able to change in example.js.

My config setting is bellow in example.js.

const config = {
    logger: console.log,
    amazonPage: 'amazon.co.jp',  
    acceptLanguage: 'ja-JP',   
    userAgent: '',          
    proxyOnly: true,          
    setupProxy: true,          
    proxyOwnIp: '192.168.2.11',        
    proxyPort: 3456,           
    proxyListenBind: '0.0.0.0',
    proxyLogLevel: 'warn',      
    amazonPageProxyLanguage: 'ja_JP', 
    formerRegistrationData: { } 
};

**Comment by naka-kazz** [comment]
I solved my problem about getting alexa cookie from alexa.amazon.co.jp by customise Alexa-cookie. For Japanese alexa, we have to login www.amazon.co.jp and get cookies from alexa.amazon.co.jp.
Thank you for your support. Change Logs are follow...

alexa-cookie.js:L494
 host: 'alexa.amazon.com' --> host: 'alexa.amazon.co.jp'

proxy.js:Replace All
  "www.amazon.com" --> "www.amazon.co.jp"
  "alexa.amazon.com" --> "alexa.amazon.co.jp"

proxy.js:L107
 "^/alexa..amazon.com" -->  "^/alexa.amazon.co.jp"

proxt.js:L136
 change "const initialUrl" to  
 `https://www.amazon.co.jp/ap/signin?showRmrMe=1&openid.return_to=https%3A%2F%2Falexa.amazon.co.jp%2F&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=amzn_dp_project_dee_jp&openid.mode=checkid_setup&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&`

proxt.js:L249
 add path of exit condition "/spa/index.html"
 
That's all.

**Comment by Apollon77** [comment]
Ok I will add it more generic in next update.

**Comment by naka-kazz** [comment]
Thank you Apollon77 !!

**Comment by Apollon77** [comment]
Please leave open that I still see it

**Comment by Apollon77** [comment]
@naka-kazz please try 3.1.0 and new parameter baseAmazonPage
