### ISSUE TITLE
Amazon auth flow appears to have changed.

### ISSUE THREAD

**Issue by tonesto7** [Apollon77/alexa-cookie#46]
It's looking like there is some sort of new clientside encryption happening now.
The proxy is returning what looks to be valid cookie data but instead of redirecting it's showing and amazon sign-on page with an error.
![image](https://user-images.githubusercontent.com/1835933/87213866-25320580-c2f6-11ea-9cda-3d4b6c74d711.png)

![image](https://user-images.githubusercontent.com/1835933/87213906-77732680-c2f6-11ea-8cc3-f607c8e2f6ce.png)

I tried to debug to see if there was a new redirect URL that I needed to catch with the proxy but nothing stood out to me.

**Comment by Apollon77** [comment]
Yes, it seems they added new security measures. We are already on it. Not ETA right now :-(

**Comment by shivan** [comment]
And I thought, I am too stupid to get this to work. Will it currently still work with manual cookie extraction?

How should 

`let cookie = { ... };`

look? My tries still were unsuccessful.

**Comment by daksh1305** [comment]
i am having the same issue as well while i am trying to log in after installing the new binding i.e amazonechocontrol 2.5.6 snapshot please can anyone help us with this issue

**Comment by sigalou** [comment]
> amazonechocontrol 2.5.6

Are you on openHab?

**Comment by Apollon77** [comment]
Yes openhab Bindung seems to be affected as well by the amazon changes.

**Comment by daksh1305** [comment]
@sigalou yes i am it seems that the auth token has been updated by amazon but has not been updated in the newly introduced binding.

**Comment by Apollon77** [comment]
please try 3.3.0

**Comment by tonesto7** [comment]
@Apollon77 I'm having users say that they are not able to get this working in the UK.  Any suggestions?  Unfortunately, I don't have any logs to work with!

**Comment by Apollon77** [comment]
If you have logs then open a new ticket please. I do not have any in account to test it.  Make sure to use the very latest library version!! And logging to info should bring something. Maybe we need debug ... can also be sent to me via email but with the reference to a new ticket please.

**Comment by sigalou** [comment]
@Apollon77 
Thank you very much for your last version and your recent modifications.
I use your library on the Alexa-API plugin for Jeedom and everything works perfectly.
http://jeedom.sigalou-domotique.fr/presentation-plugin-alexa-api-pour-jeedom
Thanks again !!
