### ISSUE TITLE
Not working outside of the USA

### ISSUE THREAD

**Issue by tmleafs** [Apollon77/alexa-cookie#48]
What log data do you need, to be able to fix access for UK and other countries?

**Comment by Apollon77** [comment]
It is indeed working fine in Germany, so "not working outsde US" is indeed a wrong statement :-)

You can define a "debug" level in the options of the library. set to "info" as a first try and provide the logs ... if you are concerned because of private data send me as email (iobroker@fischer-ka.de) and add reference to this issue in the email that I can connect the mail to the isue.

**Comment by Apollon77** [comment]
PS: make sure to set the locale parameter and such correctly (en_GB ...)

**Comment by Apollon77** [comment]
And also show your script/example config you use

**Comment by hafizchin** [comment]
Hi,

First of all thanks for all your effort in making this wonderful tool!

I can confirm that cookie is no longer captured if you are outside US (I'm from Canada).

I noticed that in proxy.js `queryParams['openid.oa2.access_token']` is always empty (@line 316) .

Here's the object that is passed to the `callbackCookie`

`{
  loginCookie: 'ubid-acbca=135-8482173-1386212; ubid-main=133-6145124-2917218; x-main=@vh1qOTDVRZT3M0jFGjtiKOoEI@SP9BQxXtJ0H@OY4dFNbGsEuDY@N?HbmolA2wZ; at-main=Atza|IwEBIG_qiA3jlE3DDXi8wIPhigywBfL8MU-w_Wl3Y71bydZFJHoa_CI6U1at6rxwZwRCxQi2Vb0TqaSJxUI9sweu7guX75BgnqmosQMTibT6slssG3ilbAVryG6UR8Qv4ZKMUJjxe7TggOu0tXF7pkrM2Gfz26eoDNCzvh306Ks-IiglZjKCj2vhlmbT3ytzYt9BX_Hk_nCp6h8Hxo_GY7ylVTNvd7-FT2GFQnO-6JF5-3dfQbgzuJY3aCoYe_m2bIZ77LjfzpaUHqIlzpKrYzXX4jpv-nyivf9rm0BRmiacbmkzQw; sess-at-main=oBHQyapHF0UeW1pl+6FIINuvKRyCVPJS/ptr1fLIRUY=; session-id=138-4228804-0119661; i18n-prefs=CAD; csm-hit=GWC7B27X9Q87VDWW1KMQ+s-DDF3EAZ35KCH4Z8XH1XC|1595534483020; session-id-time=2226254513l; session-token="7oTUGG4Som3tdCIh0gaxCF+LM2bHWIfAUZi7GP+KAeExXwHA9WJ+Bts9ILoflev2PgNcXjscNeA3+VfDduj6cVolgSk856q4mnQTDaLit1BhdHVQPonodbVGEtoxEgjl37WL3cP1t100zjl8GLDMAurApAmYEiTixtZqvugQe5n2JmEcxgezSuX82APSUdEgI9MWsn9ZLi4ckuCCB+MxUavfIlV/69KBxa8OvtaQQ34="; x-acbca="N@Ue@7jqqOupwJCkMXjzYqT6MrlZTYJ1VFKmJMc52K?iArciEHmQTpb7N50a0P4U"; at-acbca=Atza|IwEBIDfuIEDqYGK5NBYf46gp0DGylyYMeXH3d0eyXq8PYIxyN0AuWHJnLsTGFg2cMg0dlCzHMOYQglJEdeytQtityEEc74ciWFBmBcjFeyys5DWM00eN0mOdgiSaIFChOx0O-fxugGmI1p0LcuoUUyj5K_N71wjMsde5Prvze0U14_mqnFpa_wxTNIpWI29wYdJo41wL09sbICwjNAyzu-gfC3buXCbrKNpL4Sl_W7Dp2T0KHWJ6Fj2NO2XCf6CjsndA__S0Ul_eaxKoN5XYrFEdG9eHWXou8Zv6djRLn2QLBOT-pQ; sess-at-acbca="TMxGSMq2S++3eh8sbITHH/ZEA6d3D6U2KRTBJFkaaOs="; frc=xwA9Gx74oPMvIgu3Jt6fX5LZbNW45FEz/GuP9YWRprIkfZfbkg050ViZDB4evmQsLCUqmrV1OoAwWOe5Fj2aVxjSYQaPJlbA/soBp0Eb6D+/rBTINcr9PM/5UzWkGgbnNgAXo0YoPnhu8XRpBor8KwpmWKXSBKiDBpkapYKj3d6++BwJs2k6bmnDXk2uAKuCoyS+FgjGfz2ado6lqJ2BC2CrVNLyn3fdLoJQZnETKtYYthZdj4PaW2s0crd+9yG3ePBDdd32LjwVMRCiezXJlsUYdP2XxavHtF04RQWkBpBRyuVrJ9J7y1ldj25kKrUKNpE+scqWZk4VlBABJhYg24OrZzA0Gimjdb/s98abF0be1MSdTbK9/JcJ9leizRfDslz6par8I/u+945KX4OQc7Pma4PKM2wX3g==; map-md=eyJkZXZpY2VfdXNlcl9kaWN0aW9uYXJ5IjpbXSwiZGV2aWNlX3JlZ2lzdHJhdGlvbl9kYXRhIjp7InNvZnR3YXJlX3ZlcnNpb24iOiIxIn0sImFwcF9pZGVudGlmaWVyIjp7ImFwcF92ZXJzaW9uIjoiMi4yLjIyMzgzMCIsImJ1bmRsZV9pZCI6ImNvbS5hbWF6b24uZWNobyJ9fQ==',
  accessToken: undefined,
  frc: 'xwA9Gx74oPMvIgu3Jt6fX5LZbNW45FEz/GuP9YWRprIkfZfbkg050ViZDB4evmQsLCUqmrV1OoAwWOe5Fj2aVxjSYQaPJlbA/soBp0Eb6D+/rBTINcr9PM/5UzWkGgbnNgAXo0YoPnhu8XRpBor8KwpmWKXSBKiDBpkapYKj3d6++BwJs2k6bmnDXk2uAKuCoyS+FgjGfz2ado6lqJ2BC2CrVNLyn3fdLoJQZnETKtYYthZdj4PaW2s0crd+9yG3ePBDdd32LjwVMRCiezXJlsUYdP2XxavHtF04RQWkBpBRyuVrJ9J7y1ldj25kKrUKNpE+scqWZk4VlBABJhYg24OrZzA0Gimjdb/s98abF0be1MSdTbK9/JcJ9leizRfDslz6par8I/u+945KX4OQc7Pma4PKM2wX3g==',
  'map-md': 'eyJkZXZpY2VfdXNlcl9kaWN0aW9uYXJ5IjpbXSwiZGV2aWNlX3JlZ2lzdHJhdGlvbl9kYXRhIjp7InNvZnR3YXJlX3ZlcnNpb24iOiIxIn0sImFwcF9pZGVudGlmaWVyIjp7ImFwcF92ZXJzaW9uIjoiMi4yLjIyMzgzMCIsImJ1bmRsZV9pZCI6ImNvbS5hbWF6b24uZWNobyJ9fQ==',
  deviceId: '383345334431463345394233433935433537423832433745363543324436453023413249564c5635564d32573831'
}`

Hope this debug info will be able to help you resolve the issue.

**Comment by Apollon77** [comment]
This is not debug, this is the result ... I need the full debug log from the proxy login

**Comment by hafizchin** [comment]
Hi,

Here you go. Please note that I am using it in conjunction with echo speaks.

[dump.log](https://github.com/Apollon77/alexa-cookie/files/4969021/dump.log)

**Comment by Apollon77** [comment]
I thunk the problem is that the config is wrong!
You need to use amazon.com as login url. The new baseurl parameter could be amazon.ca then maybe ...

Please leave amazon.com as login Url and see if it is working then

Was it correct before to set loginUrl to amazon.ca? Because in fact the mail logic here was not touched!

**Comment by Apollon77** [comment]
Maybe this is relevant for all others too: the login url should be AND STAY amazon.com !!! Then set the correct locale. This is only different for Japan from current knowledge

The logic works as follows: login us handled by amazon.com domain, the the assigned marketplace is read for the logged in user and then the tokens are exchanged to your local marketplace tokens. I’m works that way very well for my German account.

**Comment by hafizchin** [comment]
Yes, I can can confirm that the above settings work. Thanks

**Comment by Apollon77** [comment]
@hafizchin The intersting question indeed is: Was it working in earlier version with your other settings or was it your first try? :-)

**Comment by hafizchin** [comment]
@Apollon77 yes, in fact it only stopped working around July 19 or 20. I've read in some forums that this was because amazon made some chages.

**Comment by Apollon77** [comment]
I was not really aware that people change the BaseUrl to be a local one... and wonder that this ever worked ;-)
There is basically one other change in ther which now seem to break this. I will try to change that in an update later today and then we see if it helps

**Comment by hafizchin** [comment]
@Apollon77 It would be nice if the baseUrl can't be change so that other people won't commit the same mistake that I did.

Thanks again for all your work!

**Comment by Apollon77** [comment]
Basically if it was working before :-) Maybe we get it working again

**Comment by Apollon77** [comment]
and for other encapsulated reagions like japane you neeed to change it ...

**Comment by Apollon77** [comment]
plesae try 3.4.1

**Comment by Apollon77** [comment]
Ok I close here ... reopen please if still a topic
