### ISSUE TITLE
cookie location

### ISSUE THREAD

**Issue by noureddin212** [Apollon77/alexa-cookie#5]
Hello Apollon77
I follow the example and It gives me a success cookie:

ReferenceError: config is not defined

Alexa-Cookie: Use as Login-Amazon-URL: amazon.fr
Alexa-Cookie: Use as Alexa-Service-Host: alexa.amazon.fr
Alexa-Cookie: Use as User-Agent: ...
Alexa-Cookie: Use as Accept-Language: fr-FR
Alexa-Cookie: Proxy-Mode enabled if needed: localhost:3001 to listen on 0.0.0.0
Alexa-Cookie: Step 1: get first cookie and authentication redirect
Alexa-Cookie: Sending Request with {"host":"alexa.amazon.fr","path":"","method":"GET","headers":{"DNT":"1","Upgrade-Insecure-Requests":"1","User-Agent":"...","Accept-Language":"fr-FR","Connection":"keep-alive","Accept":"*/*"}}
Alexa-Cookie: Response (302) - Redirect to https://www.amazon.fr/ap/signin?showRmrMe=1&openid.return_to=https%3A%2F%2Falexa.amazon.fr%2F&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=amzn_dp_project_dee_fr&openid.mode=checkid_setup&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&
Alexa-Cookie: Sending Request with {"host":"www.amazon.fr","path":"/ap/signin?showRmrMe=1&openid.return_to=https%3A%2F%2Falexa.amazon.fr%2F&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=amzn_dp_project_dee_fr&openid.mode=checkid_setup&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&","method":"GET","headers":{"DNT":"1","Upgrade-Insecure-Requests":"1","User-Agent":"...","Accept-Language":"fr-FR","Connection":"keep-alive","Accept":"*/*","Cookie":""},"body":""}
Alexa-Cookie: Response (200)
Alexa-Cookie: Step 2: login empty to generate session
Alexa-Cookie: Sending Request with {"host":"www.amazon.fr","path":"/ap/signin","method":"POST","headers":{"DNT":"1","Upgrade-Insecure-Requests":"1","User-Agent":"...","Accept-Language":"fr-FR","Connection":"keep-alive","Content-Type":"application/x-www-form-urlencoded","Referer":"https://www.amazon.fr/ap/signin?showRmrMe=1&openid.return_to=https%3A%2F%2Falexa.amazon.fr%2F&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=amzn_dp_project_dee_fr&openid.mode=checkid_setup&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&","Cookie":"session-id=262-0763772-4448105; session-id-time=2173556103l","Accept":"*/*"},"gzip":true,"body":"appActionToken=y4EvZUnft1TjNEyQo25Ff5j2Fj2BZCkj3D&appAction=SIGNIN&openid.return_to=ape%3AaHR0cHM6Ly9hbGV4YS5hbWF6b24uZnIv&prevRID=ape%3AVENNRkpUSzNOQkg1NTBWQ0Q4WEE%3D&workflowState=eyJ6aXAiOiJERUYiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiQTI1NktXIn0.mhkJq6d_GDazQqTEkgtEVzquxBj45OSU0mJtUAAOAsLhDMd-0kf3dw.bY_v35RGfz8SmOdG.wA4HTWsvhwETVTRlC5lABNwfdrHr6Aupp26qBGAU5icKHtROeIFQdL-Y9g1KthrThwwrx6oXFO_3xxDxpDuPo4rUxC3qCbUHA0wj1OdUyza7jbiwSOSay0g2ueRh1K5Gh1wEgUOZ5xKXWt98aO4zLfbWzfsoshRjH8RuaGxgKr9FnIx6sRzD7EEjqAaGirj3Njb96Qej9a-YeUb3WgtFPkqO5-C6Oq7bhQ3zrJPd1tHZl9DLrr7n6GLWTbcUmBcQejbiULwkOPX7NdkgqUvWMhbtB-0VEE5Cv90nBVnNChk.Nm-SowCoJsf_aNpz_im-7Q&showPasswordChecked=false"}
Alexa-Cookie: Response (200)
Alexa-Cookie: Step 3: login with filled form, referer contains session id
Alexa-Cookie: Sending Request with {"host":"www.amazon.fr","path":"/ap/signin","method":"POST","headers":{"DNT":"1","Upgrade-Insecure-Requests":"1","User-Agent":"...","Accept-Language":"fr-FR","Connection":"keep-alive","Content-Type":"application/x-www-form-urlencoded","Referer":"https://www.amazon.fr/ap/signin/262-0763772-4448105","Cookie":"session-id=262-0763772-4448105; session-id-time=2173556103l; ubid-acbfr=261-6690497-9445502","Accept":"*/*"},"gzip":true,"body":"appActionToken=y4EvZUnft1TjNEyQo25Ff5j2Fj2BZCkj3D&appAction=SIGNIN&openid.return_to=ape%3AaHR0cHM6Ly9hbGV4YS5hbWF6b24uZnIv&prevRID=ape%3AUTcwQTZEMlA0UjA4NURLVDg1Uko%3D&workflowState=eyJ6aXAiOiJERUYiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiQTI1NktXIn0.CL_hAj7EeC2mvQ5xtDfXhtERh4PCBqmSOVmgr52cTuuOrZqaX-AqPA.Pyp2XHaz5tbAJBCm.lfd7C9TEm_us_yceDTzJo9tVSa4g9S7h8DRZEtZOTDbVaNERJUAC1BIIh2b6evMtcEK3djh5uxHAstwmkAwlRhefTCHRDkRudjie6EC31EGOus96ZzBHpDx3eCTSXRoRrQFoTyIKWEQTEO8xIWPkoyxzwEqzcJZ86NcIYNHTOvYW04wyf8wJZwphtE6HNElwnNBb5T2stJc78BghbHUfPcMpLQJ9mfSu4KToqKSSiwgT4QDWMloDEdWuHhji079ZEVkqbsyP77ch5skevJdtkFqTLg.1crWjhBWaeFwOqHfuZK5YA&showPasswordChecked=false&email=xxxxxx&password=xxxxxx"}
Alexa-Cookie: Response (200)
[HPM] Proxy created: !/cookie-success  ->  https://alexa.amazon.fr
[HPM] Proxy rewrite rule created: "^/www.amazon.fr" ~> ""
[HPM] Proxy rewrite rule created: "^/alexa.amazon.fr" ~> ""
Alexa-Cookie: Proxy-Server listening on port 3001
RESULT: Error: Amazon-Login-Error: Message important !: Pour mieux protéger votre compte, veuillez saisir à nouveau votre mot de passe puis saisissez les caractères affichés dans l'image ci-dessous. You can try to get the cookie manually by opening http://localhost:3001/ with your browser. / null
Router: / / GET / {"host":"localhost:3001","connection":"keep-alive","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.84 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8","accept-encoding":"gzip, deflate, sdch, br","accept-language":"fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4","cookie":"session-id=260-8253396-0371745; session-id-time=2173552599l; csm-hit=tb:JJ3JXFGQD5PC5E9Y1P1Y+s-0RBCBW7JRVSA55MP7R5T|1542832671283&adb:adblk_yes; ubid-acbfr=260-2002289-6197740; session-token=\"UoQyfzzbe3rVy/5vz1ai1fikHzVhKi6PsV6aVc5IDMzcw5lfdYxg82u7NIOOfdOwwrxDwGlL20oTwJ4AIfEIl86fITckwBMgXzBKb6CgVGkiq7MeLnGty/2ayMUQ4HXu/sgkDE6fYFX5fYF0ML4lf4Ui57cqD7tsG5fY/jcelIyhSjCIgv4umVHKvLoWHXXHHb7Gw+Z5Qim+LoCZn7YderwcFYd7h4BafE2XOLl0UGI=\"; x-acbfr=\"VkEQKIg6mfUE9IY0ZB?dImUTXuCT?aZ8D8GEkZFuhuBpGR@ouIUGJaMiQxzjYb5l\"; at-acbfr=Atza|IwEBIMg30uh1-7l0RN0-fgfYqUA0e7nzV1poNGPLVvt7EF653NOt2enPfxdxhMKRpM2g7ZPwVRb9kFIZUJF2_gCrg7at7dr2-HD9RsoOUvJkj8wXUHCt64hUf2imOeJjDHqGxInp9xr31UjbXYdLuI1PM8uBz5CWpDiRkfeQvCNveP9HqaUmrHNgG3N_Jl8jkOJZLR_R9fYP5oE7fQsrvlZe_Xlo2wefdYnUw973vs4R9u28sQ4N4H6RdxbEKbK4LELiaQ98XD--4JaJXRYJNLXMEvXVi6V_7-7L9dHG3DXmwvywaPMbvzGKpveprnbljyBXeAaqSTr4bxisluRq7bqcLpIH-8C-TScJnrbQ1Zk-Z51qco4BTOD4AzH06-BJIha1dWhKCm-78t-Zc04SGSjOj3G5; sess-at-acbfr=\"5w63z+O4d0pmemSpQfpGJZYGNy143KU63EjIOUTe2rY=\"; sst-acbfr=Sst1|PQFLAPIDApDtI46y2P82DZE1C0OgCvhNALcXGEFxDVwWeGY1hxw5SNvHTcGOLuNjxdP6ZRshMdR_Ia19VVVDgEKV8VsKhDHXkjclRTfM4LKWVH7AJ5QSE4VdcQeSuKfwIRRTxchc-FDBlJ4M3BJss-wIrLD7tJKHo3f51Kn8mMfhfI3pvqGd8dIPh_ff929m5WA0s6vGaUlye1T2p8Dt8xPvA5snU9V5kv7jZccknvpY3KVXH-XhoMhXAwC9NP02EoX9oBTi8SS7byVjclI3pdxx3XAZcYRRzeKJH9arlAD0ZgTe4D6rhQDjsmXNP6HC_wbCYwj4JKrQxmdGiOpV2Ay8bg; csrf=1089872606"}
Alexa-Cookie: Proxy-Request: GET /
Alexa-Cookie: Proxy Response from Host: alexa.amazon.fr
Alexa-Cookie: Proxy detected SUCCESS!!
Alexa-Cookie: Proxy catched cookie: session-id=260-8253396-0371745; session-id-time=2173552599l; csm-hit=tb:JJ3JXFGQD5PC5E9Y1P1Y+s-0RBCBW7JRVSA55MP7R5T|1542832671283&adb:adblk_yes; ubid-acbfr=260-2002289-6197740; session-token="UoQyfzzbe3rVy/5vz1ai1fikHzVhKi6PsV6aVc5IDMzcw5lfdYxg82u7NIOOfdOwwrxDwGlL20oTwJ4AIfEIl86fITckwBMgXzBKb6CgVGkiq7MeLnGty/2ayMUQ4HXu/sgkDE6fYFX5fYF0ML4lf4Ui57cqD7tsG5fY/jcelIyhSjCIgv4umVHKvLoWHXXHHb7Gw+Z5Qim+LoCZn7YderwcFYd7h4BafE2XOLl0UGI="; x-acbfr="VkEQKIg6mfUE9IY0ZB?dImUTXuCT?aZ8D8GEkZFuhuBpGR@ouIUGJaMiQxzjYb5l"; at-acbfr=Atza|IwEBIMg30uh1-7l0RN0-fgfYqUA0e7nzV1poNGPLVvt7EF653NOt2enPfxdxhMKRpM2g7ZPwVRb9kFIZUJF2_gCrg7at7dr2-HD9RsoOUvJkj8wXUHCt64hUf2imOeJjDHqGxInp9xr31UjbXYdLuI1PM8uBz5CWpDiRkfeQvCNveP9HqaUmrHNgG3N_Jl8jkOJZLR_R9fYP5oE7fQsrvlZe_Xlo2wefdYnUw973vs4R9u28sQ4N4H6RdxbEKbK4LELiaQ98XD--4JaJXRYJNLXMEvXVi6V_7-7L9dHG3DXmwvywaPMbvzGKpveprnbljyBXeAaqSTr4bxisluRq7bqcLpIH-8C-TScJnrbQ1Zk-Z51qco4BTOD4AzH06-BJIha1dWhKCm-78t-Zc04SGSjOj3G5; sess-at-acbfr="5w63z+O4d0pmemSpQfpGJZYGNy143KU63EjIOUTe2rY="; sst-acbfr=Sst1|PQFLAPIDApDtI46y2P82DZE1C0OgCvhNALcXGEFxDVwWeGY1hxw5SNvHTcGOLuNjxdP6ZRshMdR_Ia19VVVDgEKV8VsKhDHXkjclRTfM4LKWVH7AJ5QSE4VdcQeSuKfwIRRTxchc-FDBlJ4M3BJss-wIrLD7tJKHo3f51Kn8mMfhfI3pvqGd8dIPh_ff929m5WA0s6vGaUlye1T2p8Dt8xPvA5snU9V5kv7jZccknvpY3KVXH-XhoMhXAwC9NP02EoX9oBTi8SS7byVjclI3pdxx3XAZcYRRzeKJH9arlAD0ZgTe4D6rhQDjsmXNP6HC_wbCYwj4JKrQxmdGiOpV2Ay8bg; csrf=1089872606
Alexa-Cookie: Step 4: get CSRF
Alexa-Cookie: Sending Request with {"host":"alexa.amazon.fr","path":"/api/language","method":"GET","headers":{"DNT":"1","User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36","Connection":"keep-alive","Referer":"https://alexa.amazon.fr/spa/index.html","Cookie":"session-id=260-8253396-0371745; session-id-time=2173552599l; csm-hit=tb:JJ3JXFGQD5PC5E9Y1P1Y+s-0RBCBW7JRVSA55MP7R5T|1542832671283&adb:adblk_yes; ubid-acbfr=260-2002289-6197740; session-token=\"UoQyfzzbe3rVy/5vz1ai1fikHzVhKi6PsV6aVc5IDMzcw5lfdYxg82u7NIOOfdOwwrxDwGlL20oTwJ4AIfEIl86fITckwBMgXzBKb6CgVGkiq7MeLnGty/2ayMUQ4HXu/sgkDE6fYFX5fYF0ML4lf4Ui57cqD7tsG5fY/jcelIyhSjCIgv4umVHKvLoWHXXHHb7Gw+Z5Qim+LoCZn7YderwcFYd7h4BafE2XOLl0UGI=\"; x-acbfr=\"VkEQKIg6mfUE9IY0ZB?dImUTXuCT?aZ8D8GEkZFuhuBpGR@ouIUGJaMiQxzjYb5l\"; at-acbfr=Atza|IwEBIMg30uh1-7l0RN0-fgfYqUA0e7nzV1poNGPLVvt7EF653NOt2enPfxdxhMKRpM2g7ZPwVRb9kFIZUJF2_gCrg7at7dr2-HD9RsoOUvJkj8wXUHCt64hUf2imOeJjDHqGxInp9xr31UjbXYdLuI1PM8uBz5CWpDiRkfeQvCNveP9HqaUmrHNgG3N_Jl8jkOJZLR_R9fYP5oE7fQsrvlZe_Xlo2wefdYnUw973vs4R9u28sQ4N4H6RdxbEKbK4LELiaQ98XD--4JaJXRYJNLXMEvXVi6V_7-7L9dHG3DXmwvywaPMbvzGKpveprnbljyBXeAaqSTr4bxisluRq7bqcLpIH-8C-TScJnrbQ1Zk-Z51qco4BTOD4AzH06-BJIha1dWhKCm-78t-Zc04SGSjOj3G5; sess-at-acbfr=\"5w63z+O4d0pmemSpQfpGJZYGNy143KU63EjIOUTe2rY=\"; sst-acbfr=Sst1|PQFLAPIDApDtI46y2P82DZE1C0OgCvhNALcXGEFxDVwWeGY1hxw5SNvHTcGOLuNjxdP6ZRshMdR_Ia19VVVDgEKV8VsKhDHXkjclRTfM4LKWVH7AJ5QSE4VdcQeSuKfwIRRTxchc-FDBlJ4M3BJss-wIrLD7tJKHo3f51Kn8mMfhfI3pvqGd8dIPh_ff929m5WA0s6vGaUlye1T2p8Dt8xPvA5snU9V5kv7jZccknvpY3KVXH-XhoMhXAwC9NP02EoX9oBTi8SS7byVjclI3pdxx3XAZcYRRzeKJH9arlAD0ZgTe4D6rhQDjsmXNP6HC_wbCYwj4JKrQxmdGiOpV2Ay8bg; csrf=1089872606","Accept":"*/*","Origin":"https://alexa.amazon.fr"}}
Alexa-Cookie: Response (200)
Alexa-Cookie: Result: csrf=1089872606, Cookie=session-id=260-8253396-0371745; session-id-time=2173552599l; csm-hit=tb:JJ3JXFGQD5PC5E9Y1P1Y+s-0RBCBW7JRVSA55MP7R5T|1542832671283&adb:adblk_yes; ubid-acbfr=260-2002289-6197740; session-token="UoQyfzzbe3rVy/5vz1ai1fikHzVhKi6PsV6aVc5IDMzcw5lfdYxg82u7NIOOfdOwwrxDwGlL20oTwJ4AIfEIl86fITckwBMgXzBKb6CgVGkiq7MeLnGty/2ayMUQ4HXu/sgkDE6fYFX5fYF0ML4lf4Ui57cqD7tsG5fY/jcelIyhSjCIgv4umVHKvLoWHXXHHb7Gw+Z5Qim+LoCZn7YderwcFYd7h4BafE2XOLl0UGI="; x-acbfr="VkEQKIg6mfUE9IY0ZB?dImUTXuCT?aZ8D8GEkZFuhuBpGR@ouIUGJaMiQxzjYb5l"; at-acbfr=Atza|IwEBIMg30uh1-7l0RN0-fgfYqUA0e7nzV1poNGPLVvt7EF653NOt2enPfxdxhMKRpM2g7ZPwVRb9kFIZUJF2_gCrg7at7dr2-HD9RsoOUvJkj8wXUHCt64hUf2imOeJjDHqGxInp9xr31UjbXYdLuI1PM8uBz5CWpDiRkfeQvCNveP9HqaUmrHNgG3N_Jl8jkOJZLR_R9fYP5oE7fQsrvlZe_Xlo2wefdYnUw973vs4R9u28sQ4N4H6RdxbEKbK4LELiaQ98XD--4JaJXRYJNLXMEvXVi6V_7-7L9dHG3DXmwvywaPMbvzGKpveprnbljyBXeAaqSTr4bxisluRq7bqcLpIH-8C-TScJnrbQ1Zk-Z51qco4BTOD4AzH06-BJIha1dWhKCm-78t-Zc04SGSjOj3G5; sess-at-acbfr="5w63z+O4d0pmemSpQfpGJZYGNy143KU63EjIOUTe2rY="; sst-acbfr=Sst1|PQFLAPIDApDtI46y2P82DZE1C0OgCvhNALcXGEFxDVwWeGY1hxw5SNvHTcGOLuNjxdP6ZRshMdR_Ia19VVVDgEKV8VsKhDHXkjclRTfM4LKWVH7AJ5QSE4VdcQeSuKfwIRRTxchc-FDBlJ4M3BJss-wIrLD7tJKHo3f51Kn8mMfhfI3pvqGd8dIPh_ff929m5WA0s6vGaUlye1T2p8Dt8xPvA5snU9V5kv7jZccknvpY3KVXH-XhoMhXAwC9NP02EoX9oBTi8SS7byVjclI3pdxx3XAZcYRRzeKJH9arlAD0ZgTe4D6rhQDjsmXNP6HC_wbCYwj4JKrQxmdGiOpV2Ay8bg; csrf=1089872606
RESULT: null / {"cookie":"session-id=260-8253396-0371745; session-id-time=2173552599l; csm-hit=tb:JJ3JXFGQD5PC5E9Y1P1Y+s-0RBCBW7JRVSA55MP7R5T|1542832671283&adb:adblk_yes; ubid-acbfr=260-2002289-6197740; session-token=\"UoQyfzzbe3rVy/5vz1ai1fikHzVhKi6PsV6aVc5IDMzcw5lfdYxg82u7NIOOfdOwwrxDwGlL20oTwJ4AIfEIl86fITckwBMgXzBKb6CgVGkiq7MeLnGty/2ayMUQ4HXu/sgkDE6fYFX5fYF0ML4lf4Ui57cqD7tsG5fY/jcelIyhSjCIgv4umVHKvLoWHXXHHb7Gw+Z5Qim+LoCZn7YderwcFYd7h4BafE2XOLl0UGI=\"; x-acbfr=\"VkEQKIg6mfUE9IY0ZB?dImUTXuCT?aZ8D8GEkZFuhuBpGR@ouIUGJaMiQxzjYb5l\"; at-acbfr=Atza|IwEBIMg30uh1-7l0RN0-fgfYqUA0e7nzV1poNGPLVvt7EF653NOt2enPfxdxhMKRpM2g7ZPwVRb9kFIZUJF2_gCrg7at7dr2-HD9RsoOUvJkj8wXUHCt64hUf2imOeJjDHqGxInp9xr31UjbXYdLuI1PM8uBz5CWpDiRkfeQvCNveP9HqaUmrHNgG3N_Jl8jkOJZLR_R9fYP5oE7fQsrvlZe_Xlo2wefdYnUw973vs4R9u28sQ4N4H6RdxbEKbK4LELiaQ98XD--4JaJXRYJNLXMEvXVi6V_7-7L9dHG3DXmwvywaPMbvzGKpveprnbljyBXeAaqSTr4bxisluRq7bqcLpIH-8C-TScJnrbQ1Zk-Z51qco4BTOD4AzH06-BJIha1dWhKCm-78t-Zc04SGSjOj3G5; sess-at-acbfr=\"5w63z+O4d0pmemSpQfpGJZYGNy143KU63EjIOUTe2rY=\"; sst-acbfr=Sst1|PQFLAPIDApDtI46y2P82DZE1C0OgCvhNALcXGEFxDVwWeGY1hxw5SNvHTcGOLuNjxdP6ZRshMdR_Ia19VVVDgEKV8VsKhDHXkjclRTfM4LKWVH7AJ5QSE4VdcQeSuKfwIRRTxchc-FDBlJ4M3BJss-wIrLD7tJKHo3f51Kn8mMfhfI3pvqGd8dIPh_ff929m5WA0s6vGaUlye1T2p8Dt8xPvA5snU9V5kv7jZccknvpY3KVXH-XhoMhXAwC9NP02EoX9oBTi8SS7byVjclI3pdxx3XAZcYRRzeKJH9arlAD0ZgTe4D6rhQDjsmXNP6HC_wbCYwj4JKrQxmdGiOpV2Ay8bg; csrf=1089872606","csrf":"1089872606"}

the question now is how to make it work with alexa-remote-control? where to put that cookie 
or I am missing a part of the code 
Your help will be much apreciated

**Comment by Apollon77** [comment]
What exactly is the problem? DO you have more stack trace then just "cookie is not defined"? Where how do you use it? in alexa-remote? Then please open issue there ... I need more information

**Comment by noureddin212** [comment]
the output here is the output of the example.js in alexa-cookie .
The question is how to use this input in alexa-remote ?
I can create the issue in alexa-remote but for me this should be reprted here the usability of this script ( I wanted to be sure that the alexa-cookie is giving the correct output here it says Alexa-Cookie: Result: csrf=1089872606, Cookie=session-id=260-8253396-0371745; session-id-....  )
I thinked that script put the cookie in the /tmp/.alexa.login is it not the case ?
Thanks for your help

**Comment by Apollon77** [comment]
Aexa-cookie is fully integrated already in alexa-remote ... OR you can put it as described here https://github.com/Apollon77/alexa-remote#alexa-remote2
