### ISSUE TITLE
Dcoument how to proper load formerRegistrationData

### ISSUE THREAD

**Issue by Lyr3x** [Apollon77/alexa-cookie#56]
I can run the script and be ablde to see debug output, however it is not clear which part is necessary to run the alexa-remote-shell script again. If copying the last part which seems to be the complete cookie the shell script says that the cookie is expired.
`formerDataStorePath: '...'` does not accept a path like "." What am i suppose to pass here?
It is also not clear to me what i should pass to the formerRegistrationData config. May you give me a hint here?

**Comment by Apollon77** [comment]
In fact when you do the first sync that part is not existing or empty. When you get back the callback in the datapbject there is a "formerRegistrationData" object in. You need to save this content and then provide on subsequent calls to "update cookies" ...
